remote_theme: pages-themes/cayman@v0.2.0
title: Weakly Supervised Spam Label Classification
description: Authors: Garrett Birch, Zairan Xiang, Ke Xu
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
