title: "Weakly Supervised Spam Label Classification"
author: "Garrett Birch, Zairan Xiang, Ke Xu"
remote_theme: jekyll-theme-midnight #pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
